# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# compile CUDA with /usr/local/cuda/bin/nvcc
CUDA_DEFINES = -DGGML_BACKEND_BUILD -DGGML_BACKEND_SHARED -DGGML_CUDA_USE_GRAPHS -DGGML_SCHED_MAX_COPIES=4 -DGGML_SHARED -DGGML_USE_NCCL -D_GNU_SOURCE -D_XOPEN_SOURCE=600 -Dggml_cuda_EXPORTS

CUDA_INCLUDES = --options-file CMakeFiles/ggml-cuda.dir/includes_CUDA.rsp

CUDA_FLAGS = -O3 -DNDEBUG -std=c++17 "--generate-code=arch=compute_89,code=[sm_89]" "--generate-code=arch=compute_86,code=[sm_86]" -Xcompiler=-fPIC -use_fast_math -extended-lambda -compress-mode=size -Xcompiler "-Wmissing-declarations -Wmissing-noreturn -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-array-bounds -Wextra-semi -Wno-pedantic"
